cam1:
  raw: "data/test-data/Cam1_firstsec.avi"
  background: "intermediate-data/Cam1_bg.png"
  video: "intermediate-data/Cam1.avi"
cam2:
  raw: "data/test-data/Cam2_firstsec.avi"
  background: "intermediate-data/Cam2_bg.png"
  video: "intermediate-data/Cam2.avi"
cam3:
  raw: "data/test-data/Cam3_firstsec.avi"
  background: "intermediate-data/Cam3_bg.png"
  video: "intermediate-data/Cam3.avi"

calibration:
  directory: "data/test-data/calibration-images"
  parameters: "data/test-data/calibration-parameters"
  output: "intermediate-data/calibration.xml"
