name: wormlab3d

channels:
  - conda-forge
  - pytorch
  - bioconda

dependencies:
  - python = 3.9
  - av = 8.0
  - flask = 2.0
  - flask_wtf = 1.0
  - gunicorn = 20.1
  - h5py = 3.2
  - matplotlib = 3.4
  - mongoengine = 0.22
  - mpi4py = 3.0.3  # pin to earlier version to avoid warnings...
  - numpy = 1.20
  - opencv = 4.5
  - pims = 0.5
  - pymongo = 3.11
  - python-blosc = 1.10
  - python-dotenv = 0.16
  - pytorch = 1.8
  - scikit-image = 0.18
  - scikit-learn = 0.24
  - snakemake
  - tensorboard = 2.4
  - torchvision = 0.9
  - pip
  - pip:
    - git+https://gitlab.com/tom-ranner/simple-worm.git@master
