name: wormlab3d

channels:
  - conda-forge
  - pytorch
  - bioconda

dependencies:
  - python = 3.9
  - numpy = 1.20
  - pytorch = 1.7
  - matplotlib = 3.3
  - pymongo = 3.11
  - mongoengine = 0.22
  - opencv = 4.5
  - pims = 0.5
  - av = 8.0
  - scikit-image = 0.18
  - snakemake
